### ISSUE TITLE
Jars on Maven published with incorrect version string for scala version

### ISSUE THREAD

**Issue by sjwalter** [jupyter-scala/jupyter-scala#212]
The Maven repo of for the scala-kernel and related packages can be found here:

https://repo1.maven.org/maven2/sh/almond/

Notably, in Maven, all scala jar packages have a suffix with _scala-version. However, they all only use the first minor version segment, and no others, so for instance all 2.11 scala jars say 2.11 and not 2.11.12.

Since the Almond packages have the entire version string (2.11.12), it breaks a bunch of tooling that can't resolve the package. Even though Ivy can find it with some effort, getting Ivy to download it doesn't work and requires hacks.

**Comment by alexarchambault** [comment]
It's not an error, it corresponds to "full" cross-versioning ([briefly mentioned in the SBT doc](https://www.scala-sbt.org/1.0/docs/Cross-Build.html), look for `CrossVersion.full`). It means that dependency depends on a particular patch version of scala (x.y.z), rather than just a major / minor version (x.y). Almond depends on the scala-compiler (via Ammonite), so depends on a particular patch version of scala.

That would allow to release a given version of Almond against multiple scala patch versions (`2.12.6` and a `2.12.7` say).

I'm surprised this isn't handled in one way or another from Maven.

**Comment by jameskoch2** [comment]
We were able to get this working. Our trouble was due to a quirk of our Pants build system.

As we're evaluating different Scala kernels we're interested in ones which isolate us from their own dependencies, so we can upgrade at our own pace. Do you know what exactly caused Ammonite to switch over to versioning this way?  Looks like it happened sometime between May and August of this year based on [Maven releases](https://search.maven.org/search?q=ammonite-repl). Is it because Ammonite uses private/less-public APIs which are known to break in the patch-evel upgrades? Or is it just known that the scala.tools.nsc namespace doesn't adhere to the general policy around binary compatibility between the patch versions?

**Comment by jameskoch2** [comment]
Answering my own Q, seems NSC is not binary-compatible across patches, as evidenced by this [diff report between 2.12.1 and 2.12.2](https://abi-laboratory.pro/?view=compat_report&lang=java&l=scala&v1=2.12.1&v2=2.12.2&obj=fc292&kind=bin).

**Comment by alexarchambault** [comment]
Don't know if that's going to solve your issue, but you can depend on `scala-kernel-api` via a provided dependency (pulled only during compilation basically). Your module will then be usable from other scala versions (with the same major / minor number, but not necessarily the same patch number). The `almond-spark` module in this repository [does that](https://github.com/jupyter-scala/jupyter-scala/blob/57b36f829796dbb75e30aa53f5f3862db5dc9825/build.sbt#L110).

**Comment by jameskoch2** [comment]
Feel free to close this issue; thanks @alexarchambault.
