### ISSUE TITLE
Scala kernel not showing up as 'available kernel'

### ISSUE THREAD

**Issue by dbl001** [jupyter-scala/jupyter-scala#25]
I downloaded jupyter-scala from git, then built from sources.

$ sbt cli/target

$ ls -l /Users/davidlaxer/jupyter-scala/cli/target/scala-2.11/

total 224

drwxr-xr-x 4 davidlaxer staff 136 Sep 21 12:39 classes
-rw-r--r-- 1 davidlaxer staff 114465 Sep 21 12:39 jupyter-scala-cli_2.11.6-0.2.0-SNAPSHOT.jar

$ sudo jupyter kernelspec install scala-2.11/

Password:

[InstallKernelSpec] Installed kernelspec in /usr/local/share/jupyter/kernels/

David-Laxers-MacBook-Pro:target davidlaxer$ jupyter kernelspec list

Available kernels:

ir
julia-0.3
matlab_kernel
python2

Why don't I see the scala2.11 kernel?

![screen shot 2015-09-21 at 2 06 12 pm](https://cloud.githubusercontent.com/assets/3105499/10005054/f4606508-6069-11e5-8d5f-e22081389775.png)

**Comment by alexarchambault** [comment]
To install jupyter-scala from sources, you should do something like
```
git clone https://github.com/alexarchambault/jupyter-scala.git
cd jupyter-scala
sbt cli/pack
cli/target/pack/bin/jupyter-scala
```

Then `ipython kernelspec list` should display `scala211`.

For the Scala 2.10 kernel, check out the `scala-2.10.x` branch, and do `sbt ++2.10.5 cli/pack` instead of `sbt cli/pack`. The kernel name is then `scala210`. Note that to have both kernels at the same time this way, you should e.g. clone the repo in two different directories.

**Comment by dbl001** [comment]
THANK YOU!

**Comment by x10ba** [comment]
Hi,
I have a question on sbt cli/pack and how to resolve since I can't access the scala kernel.
Any help is appreciated.
Thanks,
x10ba

//details
Using mac OS with following command:
sbt cli/pack

yields this error:
[error] Expected ID character
[error] Not a valid command: cli (similar: alias, plugin)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: cli (similar: clean, doc)
[error] cli/pack
[error]    ^

**Comment by mizvol** [comment]
Hi, @x10ba !

Try compiled Scala binaries. You can find them here:
https://github.com/alexarchambault/jupyter-scala#quick-start

Hope this helps.

**Comment by dbl001** [comment]
[info] Set current project to jupyter-scala (in build file:/Users/davidlaxer/jupyter-scala/)
[error] Expected ID character
[error] Not a valid command: cli (similar: alias, plugin)
[error] Expected project ID
[error] Expected configuration
[error] Expected ':' (if selecting a configuration)
[error] Expected key
[error] Not a valid key: cli (similar: clean, doc)
[error] cli/packArchive
[error]    ^

**Comment by mizvol** [comment]
@dbl001 See my answer above.
Don't try to compile the binaries. Just use the compiled binaries.

**Comment by alexarchambault** [comment]
@dbl001 @mizvol Or see the [forthcoming updated README](https://github.com/alexarchambault/jupyter-scala/tree/topic/update-readme) for the latest version. If you still want to compile the kernel yourself, substitute `scala-cli/pack` to `cli/pack`.

**Comment by dbl001** [comment]
Don’t I just run:  $sbt cli/packArchive

**Comment by sbromberger** [comment]
Hi,

I did `sbt scala-cli/packArchive` and it seemed to work. Next, however:

```
phasebang:jupyter-scala bromberger1$ cli/target/pack/bin/jupyter-scala
Cannot get main JAR path. Is jupyter-scala launched via its launcher?
```

What am I missing?

**Comment by sbromberger** [comment]
See #68 for the working process.

**Comment by dbl001** [comment]
Launching
Error: /Users/davidlaxer/.ipython/kernels/scala211/kernel.json already exists, force erasing it with --force

**Comment by alexarchambault** [comment]
@dbl001 Add the `--force` option (as the message says :-). That will replace the existing Scala 2.11 kernel.

**Comment by dbl001** [comment]
:-)

ipython console --kernel scala211


Do I run ipython or jupyter?  
Will this allow me to create a Spark 1.6 context (to my local Spark?)

**Comment by alexarchambault** [comment]
Closing this now that the [upcoming version](https://github.com/jupyter-scala/jupyter-scala/tree/develop) is about to become the default one.
