### ISSUE TITLE
Print statements within function not displyated

### ISSUE THREAD

**Issue by cliburn** [jupyter-scala/jupyter-scala#3]
``` scala
def print() : Unit = println("Hello")
print()
```

Output is

``` scala
()
```

**Comment by alexarchambault** [comment]
I confirm that. I know I fixed this some time ago, but didn't push it on github at the time. I'll close this issue once that's done.

**Comment by alexarchambault** [comment]
This is now fixed:

![jupyter-scala 3](https://cloud.githubusercontent.com/assets/7063723/7657105/aab33d6c-fb2f-11e4-977e-8a75c5b103f9.PNG)

**Comment by alexarchambault** [comment]
Although, admittedly, the output could be in reverse order (function is defined, then it is called). Re-opening until I can have a look at this.

**Comment by tekacs** [comment]
@alexarchambault Further to this, stdout that is put out after a delay doesn't display at all (beyond a small, fixed window).

Perhaps this might be hard to mesh with IPython's cells concept? (the likes of [Scastie](https://scastie.scala-lang.org) and [RunKit](https://runkit.com) solve this in a very heavyweight fashion with containers and spawning new runtimes for each output)

That said, the following:

```scala
import monix.eval.Task, monix.execution.Scheduler.Implicits.global
import scala.concurrent.duration._

Task("test").delayExecution(1.second).dump("O").subscribe()
```

The above is a simple example, but being unable to see/capture delayed output makes jupyter-scala pretty impossible to use for debugging async/delayed execution.

The above works fine in ammonite (albeit jankily, printing the output after the shell prompt), presumably because the output is fully unmanaged.

Any ideas on a path towards this use case being possible with jupyter-scala?

**Comment by alexarchambault** [comment]
@tekacs With the new kernel version (on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop) for now), one can update previously displayed values, like
```
val handle = text("foo") // displays text "foo"
handle.update("other") // updates the previous text - can be done in the background, from an another cell, etc.
```

`println` is only supposed to work while a cell is running, yes. AFAIK, jupyter only allows to send actual stdout / stderr output while a cell is running.
