### ISSUE TITLE
Cannot use Magic Commands

### ISSUE THREAD

**Issue by amotahari-rms** [jupyter-scala/jupyter-scala#44]

**Comment by alexarchambault** [comment]
Succinct, but relevant issue :-) 

The philosophy of jupyter-scala closely follows the one of [Ammonite](https://github.com/lihaoyi/Ammonite) wrt magic / special commands. Namely, there's no magic commands per se, these are replaced by a few methods that one can call directly.

In particular, one can call
- `load.ivy("org" %% "name" % "version")` to load a dependency,
- `load.resolver("some name" at "https://...")` to add a Maven resolver to load dependencies from,
- `show(value)` to display `value` without truncation,
- `display.html("some <b>HTML</b>")` to display some HTML,
- `display.js("""alert("hello")""");` to run some javascript,
- etc.

Writing a comprehensive documentation for all of these is high on my TODO list (just below putting my latest developments in shape).

**Comment by amotahari-rms** [comment]
I see, Thanks! :-)

**Comment by dabro** [comment]
I would strongly recommend implementing an interface for at least the pythong %/%% magics, given all the amazing tools out there, as a form of bootstrapping and poor-man's unix pipe/inter-language interoperability.  For example, the %capture magic to capture a cell's output in python, the various language magics, the %hierarchy magic for graphviz etc.  I think being interoperable and able to leverage all the ipython maturity would be a real selling point.

I can see two options: filtering out any commands from jupyter with these and forwarding on to an ipython kernel, or enabling scala-jupyter under the [metakernel](https://github.com/Calysto/metakernel) proxy kernel.

I ended up here because I wanted to use the %hierarchy magic for graphviz output.  If anyone else ends up here because of this note, maybe [graphviz-s](https://github.com/drdozer/graphviz-s) scala [lightning](http://lightning-viz.org/documentation/#introduction) bindings will work for you.
Just a thought.  Awesome work.

**Comment by alexarchambault** [comment]
Closing, as the upcoming version is around the corner (currently on the [`develop` branch](https://github.com/jupyter-scala/jupyter-scala/tree/develop)).
