### ISSUE TITLE
Support for JupyterLab?

### ISSUE THREAD

**Issue by analytically** [jupyter-scala/jupyter-scala#95]
https://github.com/jupyter/jupyterlab

**Comment by alexarchambault** [comment]
jupyterlab just uses the kernels from jupyter. It seems to work out-of-the-box.

**Comment by joefromct** [comment]
it out of the box however will install to `~/.local/share/jupyter/kernels/scala211` ... so i think you might have to move the kernel to `/usr/local/share/jupyter/kerners` for instance.

**Comment by PabloLeon** [comment]
I can access the jupyter scala console and jupyter notebook works with ther scala kernel. However in scala lab notebooks with the scala kernel hang/freeze. The kernel  is listed/displayed in the lab/works in the console. Any ideas? @analytically does it work for you?

**Comment by rgbkrk** [comment]
If it's breaking in jupyterlab, report it in https://github.com/jupyterlab/jupyterlab. It's a separate frontend implementation from the notebook.

**Comment by jameskoch2** [comment]
Using the very-recently-published Almond 0.1.5 on macOS, my behavior matches that described by @PabloLeon over a year ago; the kernel starts but appears to hang while evaluating an expression. Exact same kernel installation works fine in `jupyter notebook`. I haven't followed @rgbkrk 's advice to report this to the lab project only because the recent Almond build is fairly new.

**Comment by alexarchambault** [comment]
I'll have a look, I'm sure it was working fine at some point during the rewrite as almond…

**Comment by jameskoch2** [comment]
I can confirm that Almond 0.1.7 now works w/ Lab 0.34.7.
